Description=''' Feats are summarized on Table: Feats below. Note that the prerequisites and benefits of the feats on this table are abbreviated for ease of reference. See the feats description for full details.

The following format is used for all feat descriptions.

Feat Name: The feat's name also indicates what subcategory, if any, the feat belongs to, and is followed by a basic description of what the feat does.
Prerequisite: A minimum ability score, another feat or feats, a minimum base attack bonus, a minimum number of ranks in one or more skills, or anything else required in order to take the feat. This entry is absent if a feat has no prerequisite. A feat may have more than one prerequisite.
Benefit: What the feat enables the character ("you" in the feat description) to do. If a character has the same feat more than once, its benefits do not stack unless indicated otherwise in the description.
Normal: What a character who does not have this feat is limited to or restricted from doing. If not having the feat causes no particular drawback, this entry is absent.
Special: Additional unusual facts about the feat.

'''
FEATS={ "Acrobatic"                      : {"PREREQUISITES"  : "-","BENEFITS"                                                                   : "+2 bonus on Acrobatics and Fly checks"},
"Spell Mastery"                  : { "PREREQUISITES" : "1st-level Wizard" ,"BENEFITS"                                                   : "Prepare some spells without a spellbook"},
"Master Craftsman"               : { "PREREQUISITES" : "5 ranks in any Craft or Profession skill" ,"BENEFITS"                           : "You can craft magic items without being a spellcaster"},
"Disruptive"                     : { "PREREQUISITES" : "6th-level fighter" ,"BENEFITS"                                                  : "Increases the DC to cast spells adjacent to you"},
"Improved Familiar"              : { "PREREQUISITES" : "Ability to acquire a familiar, see feat" ,"BENEFITS"                            : "Gain a more powerful familiar"},
"Arcane Strike"                  : { "PREREQUISITES" : "Ability to cast arcane spells" ,"BENEFITS"                                      : "+1 damage and weapons are considered magic"},
 "Critical Mastery"              : { "PREREQUISITES" : "Any two critical feats, 14th-level fighter" ,"BENEFITS"                         : "Apply two effects to your critical hits"},
 "Armor Proficiency, Medium"     : { "PREREQUISITES" : "Armor Proficiency, Light" ,"BENEFITS"                                           : "No penalties on attack rolls while wearing medium armor"},
"Arcane Armor Training"          : { "PREREQUISITES" : "Armor Proficiency, Light, caster level 3rd" ,"BENEFITS"                         : "Reduce your arcane spell failure chance by 10%"},
 "Armor Proficiency, Heavy"      : { "PREREQUISITES" : "Armor Proficiency, Medium" ,"BENEFITS"                                          : "No penalties on attack rolls while wearing heavy armor"},
"Exra Performance"               : { "PREREQUISITES" : "Bardic performance class feature" ,"BENEFITS"                                   : "Use bardic performance for 6 additional rounds per day"},
"Exotic Weapon Proficiency"      : { "PREREQUISITES" : "Base attack bonus +1" ,"BENEFITS"                                               : "No penalty on attacks made with one exotic weapon"},
"Quick Draw"                     : { "PREREQUISITES" : "Base attack bonus +1" ,"BENEFITS"                                               : "Draw weapon as a free action"},
"Step Up"                        : { "PREREQUISITES" : "Base attack bonus +1" ,"BENEFITS"                                               : "Take a 5-foot step as an immediate action"},
"Strike Back"                    : { "PREREQUISITES" : "Base attack bonus +11" ,"BENEFITS"                                              : "Attack foes that strike you while using reach"},
"Lunge"                          : { "PREREQUISITES" : "Base attack bonus +6" ,"BENEFITS"                                               : "Take a -2 penalty to your AC to attack with reach"},
"Vital Strike"                   : { "PREREQUISITES" : "Base attack bonus +6" ,"BENEFITS"                                               : "Deal twice the normal damage on a single attack"},
"Critical Focus"                 : { "PREREQUISITES" : "Base attack bonus +9" ,"BENEFITS"                                               : "+4 bonus on attack rolls made to confirm critical hits"},
"Craft Staff"                    : { "PREREQUISITES" : "Caster level 11th" ,"BENEFITS"                                                  : "Create magic staves"},
"Scribe Scroll"                  : { "PREREQUISITES" : "Caster level 1st" ,"BENEFITS"                                                   : "Create magic scrolls"},
"Brew Potion"                    : { "PREREQUISITES" : "Caster level 3rd" ,"BENEFITS"                                                   : "Create magic potions"},
"Craft Wondrous Item"            : { "PREREQUISITES" : "Caster level 3rd" ,"BENEFITS"                                                   : "Create magic wondrous items"},
"Craft Magic Arms and Armor"     : { "PREREQUISITES" : "Caster level 5th" ,"BENEFITS"                                                   : "Create magic armors, shields, and weapons"},
"Craft Wand"                     : { "PREREQUISITES" : "Caster level 5th" ,"BENEFITS"                                                   : "Create magic wands"},
"Forge Ring"                     : { "PREREQUISITES" : "Caster level 7th" ,"BENEFITS"                                                   : "Create magic rings"},
"Craft Rod"                      : { "PREREQUISITES" : "Caster level 9th" ,"BENEFITS"                                                   : "Create magic rods"},
"Improvised Weapon Mastery"      : { "PREREQUISITES" : "Catch Off-Guard or Throw Anything, base attack bonus +8" ,"BENEFITS"            : "Make an improvised weapon deadly"},
"Selective Channeling"           : { "PREREQUISITES" : "Cha 13, channel energy class feature" ,"BENEFITS"                               : "Choose whom to affect with channel energy"},
"Channel Smite"                  : { "PREREQUISITES" : "Channel energy class feature" ,"BENEFITS"                                       : "Channel energy through your attack"},
"Elemental Channel"              : { "PREREQUISITES" : "Channel energy class feature" ,"BENEFITS"                                       : "Channel energy can harm or heal elementals"},
"Extra Channel"                  : { "PREREQUISITES" : "Channel energy class feature" ,"BENEFITS"                                       : "Channel energy two additional times per day"},
"Improved Channel"               : { "PREREQUISITES" : "Channel energy class feature" ,"BENEFITS"                                       : "+2 bonus on channel energy DC"},
"Command Undead"                 : { "PREREQUISITES" : "Channel negative energy class feature" ,"BENEFITS"                              : "Channel energy can be used to control undead"},
"Turn Undead"                    : { "PREREQUISITES" : "Channel positive energy class feature" ,"BENEFITS"                              : "Channel energy can be used to make undead flee"},
"Leadership"                     : { "PREREQUISITES" : "Character level 7th" ,"BENEFITS"                                                : "Gain a cohort and followers"},
 "Great Cleave"                  : { "PREREQUISITES" : "Cleave, base attack bonus +4" ,"BENEFITS"                                       : "Make an additional attack after each attack hits"},
 "Improved Disarm"               : { "PREREQUISITES" : "Combat Expertise" ,"BENEFITS"                                                   : "+2 bonus on disarm attempts, no attack of opportunity"},
 "Improved Feint"                : { "PREREQUISITES" : "Combat Expertise" ,"BENEFITS"                                                   : "Feint as a move action"},
 "Improved Trip"                 : { "PREREQUISITES" : "Combat Expertise" ,"BENEFITS"                                                   : "+2 bonus on trip attempts, no attack of opportunity"},
 "Stand Still"                   : { "PREREQUISITES" : "Combat Reflexes" ,"BENEFITS"                                                    : "Stop enemies from moving past you"},
 "Bleeding Critical"             : { "PREREQUISITES" : "Critical Focus, base attack bonus +11" ,"BENEFITS"                              : "Whenever you score a critical hit, the target takes 2d6 bleed"},
 "Sickening Critical"            : { "PREREQUISITES" : "Critical Focus, base attack bonus +11" ,"BENEFITS"                              : "Whenever you score a critical hit, the target is sickened"},
 "Deafening Critical"            : { "PREREQUISITES" : "Critical Focus, base attack bonus +13" ,"BENEFITS"                              : "Whenever you score a critical hit, the target is deafened"},
 "Staggering Critical"           : { "PREREQUISITES" : "Critical Focus, base attack bonus +13" ,"BENEFITS"                              : "Whenever you score a critical hit, the target is staggered"},
 "Tiring Critical"               : { "PREREQUISITES" : "Critical Focus, base attack bonus +13" ,"BENEFITS"                              : "Whenever you score a critical hit, the target is fatigued"},
 "Blinding Critical"             : { "PREREQUISITES" : "Critical Focus, base attack bonus +15" ,"BENEFITS"                              : "Whenever you score a critical hit, the target is blinded"},
 "Shatter Defenses"              : { "PREREQUISITES" : "Dazzling Display, base attack bonus +6" ,"BENEFITS"                             : "Hindered foes are flat-footed"},
"Dodge"                          : { "PREREQUISITES" : "Dex 13" ,"BENEFITS"                                                             : "+1 dodge bonus to AC"},
"Nimble Moves"                   : { "PREREQUISITES" : "Dex 13" ,"BENEFITS"                                                             : "Ignore 5 feet of difficult terrain when you move"},
 "Whirlwind Attack"              : { "PREREQUISITES" : "Dex 13, Combat Expertise, Spring Attack, base attack bonus +4" ,"BENEFITS"      : "Make one melee attack against all foes within reach"},
 "Deflect Arrows"                : { "PREREQUISITES" : "Dex 13, Improved Unarmed Strike" ,"BENEFITS"                                    : "Avoid one ranged attack per round"},
 "Improved Grapple"              : { "PREREQUISITES" : "Dex 13, Improved Unarmed Strike" ,"BENEFITS"                                    : "+2 bonus on grapple attempts, no attack of opportunity"},
 "Shot on the Run"               : { "PREREQUISITES" : "Dex 13, Mobility, Point-Blank Shot, base attack bonus +4" ,"BENEFITS"           : "Make ranged attack at any point during movement"},
 "Rapid Shot"                    : { "PREREQUISITES" : "Dex 13, Point-Blank Shot" ,"BENEFITS"                                           : "Make one extra ranged attack"},
 "Stunning Fist"                 : { "PREREQUISITES" : "Dex 13, Wis 13, Improved Unarmed Strike, base attack bonus +8" ,"BENEFITS"      : "Stun opponent with an unarmed strike"},
"Deadly Aim"                     : { "PREREQUISITES" : "Dex 13, base attack bonus +1" ,"BENEFITS"                                       : "Trade ranged attack bonus for damage"},
"Two-Weapon Fighting"            : { "PREREQUISITES" : "Dex 15" ,"BENEFITS"                                                             : "Reduce two-weapon fighting penalties"},
 "Snatch Arrows"                 : { "PREREQUISITES" : "Dex 15, Deflect Arrows" ,"BENEFITS"                                             : "Catch one ranged attack per round"},
 "Wind Stance"                   : { "PREREQUISITES" : "Dex 15, Dodge, base attack bonus +6" ,"BENEFITS"                                : "Gain 20% concealment if you move"},
 "Acrobatic Steps"               : { "PREREQUISITES" : "Dex 15, Nimble Moves" ,"BENEFITS"                                               : "Ignore 20 feet of difficult terrain when you move"},
 "Manyshot"                      : { "PREREQUISITES" : "Dex 17, Rapid Shot, base attack bonus +6" ,"BENEFITS"                           : "Shoot two arrows simultaneously"},
 "Improved Two-Weapon Fighting"  : { "PREREQUISITES" : "Dex 17, Two-Weapon Fighting, base attack bonus +6" ,"BENEFITS"                  : "Gain additional off-hand attack"},
 "Lightning Stance"              : { "PREREQUISITES" : "Dex 17, Wind Stance, base attack bonus +11" ,"BENEFITS"                         : "Gain 50% concealment if you move"},
 "Greater Two-Weapon Fighting"   : { "PREREQUISITES" : "Dex 19, Improved Two-Weapon Fighting, base attack bonus +11" ,"BENEFITS"        : "Gain a third off-hand attack"},
 "Improved PreciseShot"          : { "PREREQUISITES" : "Dex 19, Precise Shot, base attack bonus +11" ,"BENEFITS"                        : "No cover or concealment chance on ranged attacks"},
 "Spellbreaker"                  : { "PREREQUISITES" : "Disruptive, 10th-level fighter" ,"BENEFITS"                                     : "Enemies provoke attacks if their spells fail"},
 "Mobility"                      : { "PREREQUISITES" : "Dodge" ,"BENEFITS"                                                              : "+4 AC against attacks of opportunity from movement"},
 "Two-Weapon Rend"               : { "PREREQUISITES" : "Double Slice, Improved Two-Weapon Fighting, base attack bonus +11" ,"BENEFITS"  : "Rend a foe hit by both your weapons"},
 "Diehard"                       : { "PREREQUISITES" : "Endurance" ,"BENEFITS"                                                          : "Automatically stabilize and remain conscious below 0 hp"},
 "Medusa's Wrath"                : { "PREREQUISITES" : "Gorgon's Fist, base attack bonus +11" ,"BENEFITS"                               : "Make 2 extra attacks against a hindered foe"},
 "Improved Great Fortitude"      : { "PREREQUISITES" : "Great Fortitude" ,"BENEFITS"                                                    : "Once per day, you may reroll a Fortitude save"},
 "Deadly Stroke"                 : { "PREREQUISITES" : "Greater Weapon Focus, Shatter Defenses, base attack bonus +11" ,"BENEFITS"      : "Deal double damage plus 1 Con bleed"},
 "Unseat"                        : { "PREREQUISITES" : "Improved Bull Rush, Mounted Combat" ,"BENEFITS"                                 : "Knock opponents from their mounts"},
 "Greater Bull Rush"             : { "PREREQUISITES" : "Improved Bull Rush, base attack bonus +6" ,"BENEFITS"                           : "Enemies you bull rush provoke attacks of opportunity"},
 "Greater Disarm"                : { "PREREQUISITES" : "Improved Disarm, base attack bonus +6" ,"BENEFITS"                              : "Disarmed weapons are knocked away from your enemy"},
 "Greater Feint"                 : { "PREREQUISITES" : "Improved Feint, base attack bonus +6" ,"BENEFITS"                               : "Enemies you feint lose their Dex bonus for 1 round"},
 "Greater Grapple"               : { "PREREQUISITES" : "Improved Grapple, base attack bonus +6" ,"BENEFITS"                             : "Maintain your grapple as a move action"},
 "Greater Overrun"               : { "PREREQUISITES" : "Improved Overrun, base attack bonus +6" ,"BENEFITS"                             : "Enemies you overrun provoke attacks of opportunity"},
 "Pinpoint Targeting"            : { "PREREQUISITES" : "Improved Precise Shot, base attack bonus +16" ,"BENEFITS"                       : "No armor or shield bonus on one ranged attack"},
 "Shield Slam"                   : { "PREREQUISITES" : "Improved Shield Bash, Two-Weapon Fighting, base attack bonus +6" ,"BENEFITS"    : "Free bull rush with a bash attack"},
 "Greater Sunder"                : { "PREREQUISITES" : "Improved Sunder, base attack bonus +6" ,"BENEFITS"                              : "Damage from sunder attempts transfers to your enemy"},
 "Greater Trip"                  : { "PREREQUISITES" : "Improved Trip, base attack bonus +6" ,"BENEFITS"                                : "Enemies you trip provoke attacks of opportunity"},
 "Scorpion Style"                : { "PREREQUISITES" : "Improved Unarmed Strike" ,"BENEFITS"                                            : "Reduce target's speed to 5 ft."},
 "Greater Vital Strike"          : { "PREREQUISITES" : "Improved Vital Strike, base attack bonus +16" ,"BENEFITS"                       : "Deal four times the normal damage on a single attack"},
"Combat Expertise"               : { "PREREQUISITES" : "Int 13" ,"BENEFITS"                                                             : "Trade attack bonus for AC bonus"},
 "Improved Iron Will"            : { "PREREQUISITES" : "Iron Will" ,"BENEFITS"                                                          : "Once per day, you may reroll a Will save"},
"Extra Ki"                       : { "PREREQUISITES" : "Ki pool class feature" ,"BENEFITS"                                              : "Increase your ki pool by 2 points"},
"Extra Lay On Hands"             : { "PREREQUISITES" : "Lay on hands class feature" ,"BENEFITS"                                         : "Use lay on hands two additional times per day"},
 "Improved Lightning Reflexes"   : { "PREREQUISITES" : "Lightning Reflexes" ,"BENEFITS"                                                 : "Once per day, you may reroll a Reflex save"},
"Extra Mercy"                    : { "PREREQUISITES" : "Mercy class feature" ,"BENEFITS"                                                : "Your lay on hands benefits from one additional mercy"},
 "Spring Attack"                 : { "PREREQUISITES" : "Mobility, base attack bonus +4" ,"BENEFITS"                                     : "Move before and after melee attack"},
 "Mounted Archery"               : { "PREREQUISITES" : "Mounted Combat" ,"BENEFITS"                                                     : "Halve the penalty for ranged attacks while mounted"},
 "Ride-By Attack"                : { "PREREQUISITES" : "Mounted Combat" ,"BENEFITS"                                                     : "Move before and after a charge attack while mounted"},
 "Trample"                       : { "PREREQUISITES" : "Mounted Combat" ,"BENEFITS"                                                     : "Overrun targets while mounted"},
 "Greater Penetrating Strike"    : { "PREREQUISITES" : "Penetrating Strike, 16th-level fighter" ,"BENEFITS"                             : "Your attacks ignore 10 points of damage reduction"},
 "Far Shot"                      : { "PREREQUISITES" : "Point-Blank Shot" ,"BENEFITS"                                                   : "Decrease ranged penalties by half"},
 "Precise Shot"                  : { "PREREQUISITES" : "Point-Blank Shot" ,"BENEFITS"                                                   : "No penalty for shooting into melee"},
 "Cleave"                        : { "PREREQUISITES" : "Power Attack" ,"BENEFITS"                                                       : "Make an additional attack if the first one hits"},
 "Improved Bull Rush"            : { "PREREQUISITES" : "Power Attack" ,"BENEFITS"                                                       : "+2 bonus on bull rush attempts, no attack of opportunity"},
 "Improved Overrun"              : { "PREREQUISITES" : "Power Attack" ,"BENEFITS"                                                       : "+2 bonus on overrun attempts, no attack of opportunity"},
 "Improved Sunder"               : { "PREREQUISITES" : "Power Attack" ,"BENEFITS"                                                       : "+2 bonus on sunder attempts, no attack of opportunity"},
"Item Creation Feats"            : { "PREREQUISITES" : "Prerequisites" ,"BENEFITS"                                                      : "Benefits"},
"Metamagic Feats"                : { "PREREQUISITES" : "Prerequisites" ,"BENEFITS"                                                      : "Benefits"},
"Weapon Focus"                   : { "PREREQUISITES" : "Proficiency with weapon, base attack bonus +1" ,"BENEFITS"                      : "+1 bonus on attack rolls with one weapon"},
"Improved Critical"              : { "PREREQUISITES" : "Proficiency with weapon, base attack bonus +8" ,"BENEFITS"                      : "Double the threat range of one weapon"},
"Extra Rage"                     : { "PREREQUISITES" : "Rage class feature" ,"BENEFITS"                                                 : "Use rage for 6 additional rounds per day"},
"Mounted Combat"                 : { "PREREQUISITES" : "Ride 1 rank" ,"BENEFITS"                                                        : "Avoid attacks on mount with Ride check"},
 "Spirited Charge"               : { "PREREQUISITES" : "Ride-By Attack" ,"BENEFITS"                                                     : "Double damage on a mounted charge"},
 "Gorgons Fist"                  : { "PREREQUISITES" : "Scorpion Style, base attack bonus +6" ,"BENEFITS"                               : "Stagger a foe whose speed is reduced"},
 "Greater Shield Focus"          : { "PREREQUISITES" : "Shield Focus, 8th-level fighter" ,"BENEFITS"                                    : "Gain a +1 bonus to your AC when using a shield"},
 "Improved Shield Bash"          : { "PREREQUISITES" : "Shield Proficiency" ,"BENEFITS"                                                 : "Keep your shield bonus when shield bashing"},
 "Tower Shield Proficiency"      : { "PREREQUISITES" : "Shield Proficiency" ,"BENEFITS"                                                 : "No penalties on attack rolls when using a tower shield"},
 "Shield Focus"                  : { "PREREQUISITES" : "Shield Proficiency, base attack bonus +1" ,"BENEFITS"                           : "Gain a +1 bonus to your AC when using a shield"},
 "Shield Master"                 : { "PREREQUISITES" : "Shield Slam, base attack bonus +11" ,"BENEFITS"                                 : "No two-weapon penalties when attacking with a shield"},
 "Greater Spell Focus"           : { "PREREQUISITES" : "Spell Focus" ,"BENEFITS"                                                        : "+1 bonus on save DCs for one school"},
"Augment Summoning"              : { "PREREQUISITES" : "Spell Focus (conjuration)" ,"BENEFITS"                                          : "Summoned creatures gain +4 Str and Con"},
"Greater Spell Penetration"      : { "PREREQUISITES" : "Spell Penetration" ,"BENEFITS"                                                  : "+2 bonus on level checks to beat spell resistance"},
 "Stunning Critical"             : { "PREREQUISITES" : "Staggering Critical, base attack bonus +17" ,"BENEFITS"                         : "Whenever you score a critical hit, the target is stunned"},
"Power Attack"                   : { "PREREQUISITES" : "Str 13, base attack bonus +1" ,"BENEFITS"                                       : "Trade melee attack bonus for damage"},
 "Exhausting Critical"           : { "PREREQUISITES" : "Tiring Critical, base attack bonus +15" ,"BENEFITS"                             : "Whenever you score a critical hit, the target is exhausted"},
 "Double Slice"                  : { "PREREQUISITES" : "Two-Weapon Fighting" ,"BENEFITS"                                                : "Add your Str bonus to off-hand damage rolls"},
 "Two-Weapon Defense"            : { "PREREQUISITES" : "Two-Weapon Fighting" ,"BENEFITS"                                                : "Gain +1 shield bonus when fighting with two weapons"},
 "Improved Vital Strike"         : { "PREREQUISITES" : "Vital Strike, base attack bonus +11" ,"BENEFITS"                                : "Deal three times the normal damage on a single attack"},
 "Dazzling Display"              : { "PREREQUISITES" : "Weapon Focus" ,"BENEFITS"                                                       : "Intimidate all foes within 30 feet"},
 "Penetrating Strike"            : { "PREREQUISITES" : "Weapon Focus, 12th-level fighter" ,"BENEFITS"                                   : "Your attacks ignore 5 points of damage reduction"},
 "Weapon Specialization"         : { "PREREQUISITES" : "Weapon Focus, 4th-level fighter" ,"BENEFITS"                                    : "+2 bonus on damage rolls with one weapon"},
 "Greater Weapon Focus"          : { "PREREQUISITES" : "Weapon Focus, 8th-level fighter" ,"BENEFITS"                                    : "+1 bonus on attack rolls with one weapon"},
 "Greater Weapon Specialization" : { "PREREQUISITES" : "Weapon Specialization, 12th-level fighter" ,"BENEFITS"                          : "+2 bonus on damage rolls with one weapon"},
"Rapid Reload"                   : { "PREREQUISITES" : "Weapon proficiency (crossbow)" ,"BENEFITS"                                      : "Reload crossbow quickly"},
"Natural Spell"                  : { "PREREQUISITES" : "Wis 13, wild shape class feature" ,"BENEFITS"                                   : "Cast spells while using wild shape"},
"Arcane Armor Mastery"           : { "PREREQUISITES" : "Arcane Armor Training, Armor Proficiency, Medium, caster level 7th" ,"BENEFITS" : "Reduce your arcane spell failure chance by 20%"},
"Agile Maneuvers"                : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "Use your Dex bonus when calculating your CMB"},
"Alertness"                      : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "+2 bonus on Perception and Sense Motive checks"},
"Animal Affinity"                : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "+2 bonus on Handle Animal and Ride checks"},
"Armor Proficiency, Light"       : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "No penalties on attack rolls while wearing light armor"},
"Athletic"                       : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "+2 bonus on Climb and Swim checks"},
"Blind-Fight"                    : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "Reroll miss chances for concealment"},
"Catch Off-Guard"                : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "No penalties for improvised melee weapons"},
"Combat Casting"                 : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "+4 bonus on concentration checks for casting defensively"},
"Combat Reflexes"                : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "Make additional attacks of opportunity"},
"Deceitful"                      : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "+2 bonus on Bluff and Disguise checks"},
"Defensive Combat Training"      : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "Use your total Hit Dice as your base attack bonus for CMD"},
"Deft Hands"                     : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "+2 bonus on Disable Device and Sleight of Hand checks"},
"Empower Spell"                  : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "Increase spell variables by 50%"},
"Endurance"                      : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "+4 bonus on checks to avoid nonlethal damage"},
"Enlarge Spell"                  : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "Double spell range"},
"Eschew Materials"               : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "Cast spells without material components"},
"Extend Spell"                   : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "Double spell duration"},
"Fleet"                          : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "Your base speed increases by 5 feet"},
"Great Fortitude"                : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "+2 on Fortitude saves"},
"Heighten Spell"                 : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "Treat spell as a higher level"},
"Improved Counterspell"          : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "Counterspell with spell of the same school"},
"Improved Initiative"            : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "+4 bonus on initiative checks"},
"Improved Unarmed Strike"        : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "Always considered armed"},
"Intimidating Prowess"           : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "Add Str to Intimidate in addition to Cha"},
"Iron Will"                      : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "+2 bonus on Will saves"},
"Lightning Reflexes"             : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "+2 bonus on Reflex saves"},
"Magical Aptitude"               : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "+2 bonus on Spellcraft and Use Magic Device checks"},
"Martial Weapon Proficiency"     : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "No penalty on attacks made with one martial weapon"},
"Maximize Spell"                 : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "Maximize spell variables"},
"Persuasive"                     : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "+2 bonus on Diplomacy and Intimidate checks"},
"Point-Blank Shot"               : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "+1 attack and damage on targets within 30 feet"},
"Quicken Spell"                  : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "Cast spell as a swift action"},
"Run"                            : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "Run at 5 times your normal speed"},
"Self-Sufficient"                : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "+2 bonus on Heal and Survival checks"},
"Shield Proficiency"             : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "No penalties on attack rolls when using a shield"},
"Silent Spell"                   : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "Cast spell without verbal components"},
"Simple Weapon Proficiency"      : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "No penalty on attacks made with simple weapons"},
"Skill Focus"                    : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "+3 bonus on one skill (+6 at 10 ranks)"},
"Spell Focus"                    : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "+1 bonus on save DCs for one school"},
"Spell Penetration"              : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "+2 bonus on level checks to beat spell resistance"},
"Stealthy"                       : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "+2 bonus on Escape Artist and Stealth checks"},
"Still Spell"                    : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "Cast spell without somatic components"},
"Throw Anything"                 : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "No penalties for improvised ranged weapons"},
"Toughness"                      : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "+3 hit points, +1 per Hit Die beyond 3"},
"Weapon Finesse"                 : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "Use Dex instead of Str on attack rolls with light weapons"},
"Widen Spell"                    : {"PREREQUISITES"  : "-" ,"BENEFITS"                                                                  : "Double spell area"},
"Alignment Channel"              : {"PREREQUISITES"  : "Channel energy class feature" ,"BENEFITS"                                       : "Channel energy can heal or harm outsiders"}}

